# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  simpletron_lang__config = debug

else ifeq ($(config),release)
  simpletron_lang__config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := simpletron-lang_

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

simpletron-lang_:
ifneq (,$(simpletron_lang__config))
	@echo "==== Building simpletron-lang_ ($(simpletron_lang__config)) ===="
	@${MAKE} --no-print-directory -C . -f simpletron-lang_.make config=$(simpletron_lang__config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f simpletron-lang_.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   simpletron-lang_"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"